#!/bin/bash

# This file is part of the shareterm project
# Copyright (C) 2011  Adrien LELONG
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#Install script on target PC

GUESTUSERNAME=guest

chmod u+s /usr/bin/screen
chmod 755 /var/run/screen

if ! grep $GUESTUSERNAME /etc/passwd; then
    useradd -m -s /usr/bin/screenshell $GUESTUSERNAME
fi

mkdir -p /var/lib/shareterm
{
    echo "multiuser on"
    echo "addacl $GUESTUSERNAME"
} > /var/lib/shareterm/screenmu

if ! grep $GUESTUSERNAME /etc/sudoers; then
    echo 'ALL ALL=('$GUESTUSERNAME') NOPASSWD: ALL' >> /etc/sudoers
fi

cp bin/* /usr/bin/

