#!/bin/bash

# This file is part of the shareterm project
# Copyright (C) 2011-2012  Adrien LELONG
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#Install script on server

SHARETERMBIN=/usr/share/shareterm
SHARETERMRUN=/var/run/shareterm

if grep shareterm /etc/groups; then
    echo 'Shareterm seems to be already installed'
    exit 1
fi

groupadd shareterm
if ! grep shareterm /etc/passwd; then
    useradd shareterm -s /bin/bash -g shareterm
fi

mkdir $SHARETERMRUN
chown shareterm $SHARETERMRUN
mkdir $SHARETERMBIN

cp bin/createlink $SHARETERMBIN
cp bin/jointerm.priv $SHARETERMBIN
cp bin/server.setenv.bash $SHARETERMBIN

chown -R shareterm $SHARETERMBIN
chmod 700 $SHARETERMBIN

if ! grep shareterm /etc/sudoers; then
    echo '%shareterm ALL=(shareterm) NOPASSWD: ALL' >> /etc/sudoers
fi

